require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'vetmap' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
  #       def pod.build_type;
  #         # Uncomment one line depending on your CocoaPods version 
  #         Pod::BuildType.static_library # >= 1.9 
  #         # Pod::Target::BuildType.static_library # < 1.9 
  #       end
  #     end
  #   end
  # end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'Firebase/Analytics'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  target 'vetmapTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'vetmap-tvOS' do
  # Pods for vetmap-tvOS

  target 'vetmap-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
