$RNFirebaseAsStaticFramework = true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


target 'vetmap' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
  #       def pod.build_type;
  #         # Uncomment one line depending on your CocoaPods version 
  #         Pod::BuildType.static_library # >= 1.9 
  #         # Pod::Target::BuildType.static_library # < 1.9 
  #       end
  #     end
  #   end
  # end
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.start_with?('RNFB')
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
  use_native_modules!

  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'

  # use_frameworks! :linkage => :static

  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'Firebase/Analytics'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  target 'vetmapTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('iOSPhotoEditor')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
    end
  end

  # Follow [Flipper iOS Setup Guidelines](https://fbflipper.com/docs/getting-started/ios-native)
  # This is required because iOSPhotoEditor is implemented using Swift and we have to use use_frameworks! in Podfile
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
    'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'vetmap-tvOS' do
  # Pods for vetmap-tvOS

  target 'vetmap-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
